name: website

# Don't forget to enter the folder, e.g. with `cd test`.
executables:
  # The tests are done with firefox because chrome is
  # often added as a stable prefix in third-party linux
  # distributions and firefox is almost always in the default distribution repositories.
  #
  # Build_runner calls google-chrome, but with the prefix.
  # it turns out google-chrome-stable, which makes build_runner unable to run the tests.
  #
  # The best solution at the moment, is to change the platform from chrome to firefox.
  test: dart run build_runner test -- -p firefox
  dev: webdev serve --auto=refresh
  serve: webdev serve --release
  build: webdev build --release --output ./docs

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  test: ^1.23.0
  build_runner: ^2.3.3
  build_test: ^2.1.6
  build_web_compilers: ^3.2.7
  lints: ^2.0.1
  reio:
    path: ../core
